[package]
name = "buyo"
version = "0.1.0"
edition = "2021"

[dependencies]
oorandom = "11.1.5"
speedy2d = {version = "2.1.0", features = []}
log = "0.4"
wasm-logger = "0.2"
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.100"
