[package]
name = "blockstackers_core"
version = "0.1.0"
edition = "2021"

[dependencies]
oorandom = "11.1.5"
regex = "1.11.1"
strum = "0.27.1"
strum_macros = "0.27.1"
# speedy2d = {version = "2.1.0", features = []}
